//! Fail-closed capability and operator-control laws.

/// Secret capability proving that a request came through the operator boundary.
///
/// The token deliberately implements neither [`Clone`] nor [`Debug`], preventing
/// accidental duplication or disclosure through ordinary logs.
pub struct OperatorToken([u8; 32]);

impl OperatorToken {
    /// Wraps token bytes generated by the external authority root.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }
}

/// Authority failures are explicit and stable enough to ledger.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AuthorityError {
    /// A child requested authority unavailable to its parent.
    CapabilityEscalation,
    /// A candidate attempted an operator-only transition.
    OperatorRequired,
}

/// Capabilities carried by a runtime worker.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilitySet(u8);

impl CapabilitySet {
    const WORKSPACE_WRITE: u8 = 0b01;
    const NETWORK: u8 = 0b10;

    /// Creates a capability set from the two initial authority dimensions.
    #[must_use]
    pub const fn new(workspace_write: bool, network: bool) -> Self {
        Self((workspace_write as u8 * Self::WORKSPACE_WRITE) | (network as u8 * Self::NETWORK))
    }

    /// Derives a child capability set without permitting authority escalation.
    ///
    /// # Errors
    ///
    /// Returns [`AuthorityError::CapabilityEscalation`] when `requested`
    /// contains any capability absent from the parent.
    pub const fn derive_child(self, requested: Self) -> Result<Self, AuthorityError> {
        if requested.0 & !self.0 != 0 {
            return Err(AuthorityError::CapabilityEscalation);
        }

        Ok(requested)
    }
}

/// Persistent operator freeze state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FreezeState {
    frozen: bool,
    operator_token: [u8; 32],
}

impl FreezeState {
    /// Creates an engaged freeze state.
    #[must_use]
    pub const fn frozen(operator: &OperatorToken) -> Self {
        Self {
            frozen: true,
            operator_token: operator.0,
        }
    }

    /// Reports whether evolution remains frozen.
    #[must_use]
    pub const fn is_frozen(self) -> bool {
        self.frozen
    }

    /// Clears the freeze only with the authority root's operator token.
    ///
    /// # Errors
    ///
    /// Returns [`AuthorityError::OperatorRequired`] for invalid proofs.
    pub const fn unfreeze(&mut self, proof: &OperatorToken) -> Result<(), AuthorityError> {
        if !token_matches(&self.operator_token, &proof.0) {
            return Err(AuthorityError::OperatorRequired);
        }

        self.frozen = false;
        Ok(())
    }
}

const fn token_matches(expected: &[u8; 32], actual: &[u8; 32]) -> bool {
    let mut difference = 0;
    let mut index = 0;
    while index < expected.len() {
        difference |= expected[index] ^ actual[index];
        index += 1;
    }
    difference == 0
}
